# Maps with pathway outputs

In [1]:
import pandas as pd
import os

In [2]:
dir_output = os.path.join('output', 'sparky1111111111', 'combined')

# Create a new maps/ dir for outputs.
dir_output_maps = os.path.join(dir_output, 'maps')
try:
    os.mkdir(dir_output_maps)
except FileExistsError:
    # The directory already exists.
    pass

In [3]:
# Load in the data

df_units = pd.read_csv(
    os.path.join(dir_output, 'df_units.csv'),
    index_col=0,
    header=[0, 1],
)
df_transfer = pd.read_csv(
    os.path.join(dir_output, 'df_transfer.csv'),
    index_col=[0, 1],
    header=[0, 1],
)
df_lsoa = pd.read_csv(
    os.path.join(dir_output, 'df_lsoa.csv'),
    index_col=[0, 1],
    header=[0, 1],
)
df_results_lsoa = pd.read_csv(
    os.path.join(dir_output, 'results_summary_by_lsoa.csv'),
    index_col=[0, 1],
    header=[0, 1, 2],
)

In [4]:
df_units.head(3)

scenario                                        any             \
property                                stroke_team short_code
postcode
B152TH         Queen Elizabeth Hospital, Birmingham         QE
B714HJ    Sandwell District Hospital, West Bromwich         SW
B95SS                Birmingham Heartlands Hospital         BM

scenario                                                 \
property                          ssnap_name  lsoa_code
postcode
B152TH    Queen Elizabeth Hospital Edgbaston  E01033562
B714HJ            Sandwell District Hospital  E01010104
B95SS         Birmingham Heartlands Hospital  E01009341

scenario                                                                 \
property                                 region region_code region_type
postcode
B152TH    NHS Birmingham and Solihull ICB - 15E   E38000258       SICBL
B714HJ            NHS Black Country ICB - D2P2L   E38000259       SICBL
B95SS     NHS Birmingham and Solihull ICB - 15E   E38000258       SICBL

scenario                                                              \
property  country                                                icb
postcode
B152TH    England  NHS Birmingham and Solihull Integrated Care Board
B714HJ    England            NHS Black Country Integrated Care Board
B95SS     England  NHS Birmingham and Solihull Integrated Care Board

scenario             ... drip-and-ship                          \
property   icb_code  ...       use_ivt use_mt use_msu selected
postcode             ...
B152TH    E54000055  ...             1      1       1        0
B714HJ    E54000062  ...             1      0       0        0
B95SS     E54000055  ...             0      0       0        0

scenario                        mothership                          \
property transfer_unit_postcode    use_ivt use_mt use_msu selected
postcode
B152TH                  nearest          1      1       1        0
B714HJ                  nearest          0      0       0        0
B95SS                   nearest          0      0       0        0

scenario
property transfer_unit_postcode
postcode
B152TH                  nearest
B714HJ                  nearest
B95SS                   nearest

[3 rows x 21 columns]

In [5]:
df_transfer.head(5)

scenario                                              any drip-and-ship  \
property                        transfer_unit_travel_time      selected
postcode transfer_unit_postcode
B152TH   B152TH                                       0.0           0.0
B714HJ   B152TH                                      18.7           0.0
         NaN                                          NaN           NaN
B95SS    NaN                                          NaN           0.0
BA13NG   BS105NB                                     33.7           1.0

scenario                        mothership
property                          selected
postcode transfer_unit_postcode
B152TH   B152TH                        0.0
B714HJ   B152TH                        NaN
         NaN                           0.0
B95SS    NaN                           0.0
BA13NG   BS105NB                       NaN

In [6]:
df_lsoa.head(3)

scenario                   any drip-and-ship                            \
property            admissions unit_postcode unit_travel_time selected
lsoa      lsoa_code
Adur 001A E01031349   1.333333        BN25BE             17.6        0
Adur 001B E01031350   1.666667        BN25BE             18.7        0
Adur 001C E01031351   2.000000       BN112DH             17.6        0

scenario                                  mothership                   \
property            relative_frequency unit_postcode unit_travel_time
lsoa      lsoa_code
Adur 001A E01031349                NaN        BN25BE             17.6
Adur 001B E01031350                NaN        BN25BE             18.7
Adur 001C E01031351                NaN        BN25BE             19.8

scenario
property            selected relative_frequency
lsoa      lsoa_code
Adur 001A E01031349        0                NaN
Adur 001B E01031350        0                NaN
Adur 001C E01031351        0                NaN

In [7]:
df_results_lsoa.head(3)

scenario                                            drip-and-ship       \
property                                    time_ambulance_called
subtype                                                      mean  std
lsoa                              lsoa_code
Bath and North East Somerset 001A E01014399                  30.0  NaN
Bath and North East Somerset 001B E01014400                  30.0  0.0
Bath and North East Somerset 001C E01014401                  30.0  0.0

scenario                                                                 \
property                                    time_ambulance_arrival
subtype                                                       mean  std
lsoa                              lsoa_code
Bath and North East Somerset 001A E01014399                   60.0  NaN
Bath and North East Somerset 001B E01014400                   60.0  0.0
Bath and North East Somerset 001C E01014401                   60.0  0.0

scenario                                                                      \
property                                    time_ambulance_leaves_scene
subtype                                                            mean  std
lsoa                              lsoa_code
Bath and North East Somerset 001A E01014399                        80.0  NaN
Bath and North East Somerset 001B E01014400                        80.0  0.0
Bath and North East Somerset 001C E01014401                        80.0  0.0

scenario                                                                      \
property                                    time_admitting_unit_arrival
subtype                                                            mean  std
lsoa                              lsoa_code
Bath and North East Somerset 001A E01014399                        99.8  NaN
Bath and North East Somerset 001B E01014400                        97.6  0.0
Bath and North East Somerset 001C E01014401                        98.7  0.0

scenario                                                      ...  \
property                                    time_needle       ...
subtype                                            mean  std  ...
lsoa                              lsoa_code                   ...
Bath and North East Somerset 001A E01014399         NaN  NaN  ...
Bath and North East Somerset 001B E01014400       127.6  0.0  ...
Bath and North East Somerset 001C E01014401       128.7  0.0  ...

scenario                                       mothership                      \
property                                    utility_shift             mRS 0-2
subtype                                              mean       std      mean
lsoa                              lsoa_code
Bath and North East Somerset 001A E01014399           NaN       NaN       NaN
Bath and North East Somerset 001B E01014400      0.127088  0.052150  0.611744
Bath and North East Somerset 001C E01014401      0.142142  0.063871  0.574786

scenario                                               \
property
subtype                                           std
lsoa                              lsoa_code
Bath and North East Somerset 001A E01014399       NaN
Bath and North East Somerset 001B E01014400  0.128026
Bath and North East Somerset 001C E01014401  0.156799

scenario                                    diff_drip-and-ship_minus_mothership  \
property                                                          utility_shift
subtype                                                                    mean
lsoa                              lsoa_code
Bath and North East Somerset 001A E01014399                                 NaN
Bath and North East Somerset 001B E01014400                           -0.024411
Bath and North East Somerset 001C E01014401                           -0.043112

scenario                                                                   \
property                                              mRS shift
subtype                                           std      mean       std
lsoa                              lsoa_code
Bath and North East Somerset 001A E01014399       NaN       NaN       NaN
Bath and North East Somerset 001B E01014400  0.052648  0.123418  0.248877
Bath and North East Somerset 001C E01014401  0.063871  0.203367  0.304398

scenario
property                                      mRS 0-2
subtype                                          mean       std
lsoa                              lsoa_code
Bath and North East Somerset 001A E01014399       NaN       NaN
Bath and North East Somerset 001B E01014400  0.016226  0.186040
Bath and North East Somerset 001C E01014401  0.113098  0.156799

[3 rows x 46 columns]

In [8]:
import classes.geo_creation as gc

In [9]:
df_regions = gc.load_regions()

In [10]:
df_regions

                                                                       any  \
                                                               region_type
region                                             region_code
Aneurin Bevan University Health Board              W11000028           LHB
NHS Bath and North East Somerset, Swindon and W... E38000231         SICBL
Betsi Cadwaladr University Health Board            W11000023           LHB
NHS Bedfordshire, Luton and Milton Keynes ICB -... E38000249         SICBL
NHS Black Country ICB - D2P2L                      E38000259         SICBL
...                                                                    ...
NHS West Yorkshire ICB - 02T                       E38000025         SICBL
NHS West Yorkshire ICB - 03R                       E38000190         SICBL
NHS West Yorkshire ICB - 15F                       E38000225         SICBL
NHS West Yorkshire ICB - 36J                       E38000232         SICBL
NHS West Yorkshire ICB - X2C4Y                     E38000254         SICBL

                                                                           \
                                                               short_code
region                                             region_code
Aneurin Bevan University Health Board              W11000028           AB
NHS Bath and North East Somerset, Swindon and W... E38000231           BA
Betsi Cadwaladr University Health Board            W11000023           BC
NHS Bedfordshire, Luton and Milton Keynes ICB -... E38000249           BD
NHS Black Country ICB - D2P2L                      E38000259           BL
...                                                                   ...
NHS West Yorkshire ICB - 02T                       E38000025          WY1
NHS West Yorkshire ICB - 03R                       E38000190          WY2
NHS West Yorkshire ICB - 15F                       E38000225          WY3
NHS West Yorkshire ICB - 36J                       E38000232          WY4
NHS West Yorkshire ICB - X2C4Y                     E38000254          WY5

                                                                         \
                                                                country
region                                             region_code
Aneurin Bevan University Health Board              W11000028      Wales
NHS Bath and North East Somerset, Swindon and W... E38000231    England
Betsi Cadwaladr University Health Board            W11000023      Wales
NHS Bedfordshire, Luton and Milton Keynes ICB -... E38000249    England
NHS Black Country ICB - D2P2L                      E38000259    England
...                                                                 ...
NHS West Yorkshire ICB - 02T                       E38000025    England
NHS West Yorkshire ICB - 03R                       E38000190    England
NHS West Yorkshire ICB - 15F                       E38000225    England
NHS West Yorkshire ICB - 36J                       E38000232    England
NHS West Yorkshire ICB - X2C4Y                     E38000254    England

                                                                                                                   \
                                                                                                              icb
region                                             region_code
Aneurin Bevan University Health Board              W11000028                                                  NaN
NHS Bath and North East Somerset, Swindon and W... E38000231    NHS Bath and North East Somerset, Swindon and ...
Betsi Cadwaladr University Health Board            W11000023                                                  NaN
NHS Bedfordshire, Luton and Milton Keynes ICB -... E38000249    NHS Bedfordshire, Luton and Milton Keynes Inte...
NHS Black Country ICB - D2P2L                      E38000259              NHS Black Country Integrated Care Board
...                                                                                                           ...
NHS West Yorkshire ICB - 02T                       E38000025             NHS West Yorkshire Integrated Care Board
NHS West Yorkshire ICB - 03R                       E38000190             NHS West Yorkshire Integrated Care Board
NHS West Yorkshire ICB - 15F                       E38000225             NHS West Yorkshire Integrated Care Board
NHS West Yorkshire ICB - 36J                       E38000232             NHS West Yorkshire Integrated Care Board
NHS West Yorkshire ICB - X2C4Y                     E38000254             NHS West Yorkshire Integrated Care Board

                                                                           \
                                                                 icb_code
region                                             region_code
Aneurin Bevan University Health Board              W11000028          NaN
NHS Bath and North East Somerset, Swindon and W... E38000231    E54000040
Betsi Cadwaladr University Health Board            W11000023          NaN
NHS Bedfordshire, Luton and Milton Keynes ICB -... E38000249    E54000024
NHS Black Country ICB - D2P2L                      E38000259    E54000062
...                                                                   ...
NHS West Yorkshire ICB - 02T                       E38000025    E54000054
NHS West Yorkshire ICB - 03R                       E38000190    E54000054
NHS West Yorkshire ICB - 15F                       E38000225    E54000054
NHS West Yorkshire ICB - 36J                       E38000232    E54000054
NHS West Yorkshire ICB - X2C4Y                     E38000254    E54000054


                                                                                               isdn
region                                             region_code
Aneurin Bevan University Health Board              W11000028                                    NaN
NHS Bath and North East Somerset, Swindon and W... E38000231    Gloucester, BSW, BNSSG and Somerset
Betsi Cadwaladr University Health Board            W11000023                                    NaN
NHS Bedfordshire, Luton and Milton Keynes ICB -... E38000249                East of England (South)
NHS Black Country ICB - D2P2L                      E38000259                         North Midlands
...                                                                                             ...
NHS West Yorkshire ICB - 02T                       E38000025           West Yorkshire and Harrogate
NHS West Yorkshire ICB - 03R                       E38000190           West Yorkshire and Harrogate
NHS West Yorkshire ICB - 15F                       E38000225           West Yorkshire and Harrogate
NHS West Yorkshire ICB - 36J                       E38000232           West Yorkshire and Harrogate
NHS West Yorkshire ICB - X2C4Y                     E38000254           West Yorkshire and Harrogate

[113 rows x 6 columns]

In [11]:
(
    gdf_boundaries_regions,
    gdf_units,
    gdf_lines_transfer,
    gdf_boundaries_lsoa,
    gdf_boundaries_catchment
) = gc.make_all_geometry_data(
    df_lsoa, df_units, df_regions, df_transfer, df_results_lsoa
    )

In [12]:
gdf_boundaries_regions.head(3)

scenario                                                           any  \
property                                                         BNG_E
region                                             region_code
Aneurin Bevan University Health Board              W11000028    331785
NHS Bath and North East Somerset, Swindon and W... E38000231    393349
Betsi Cadwaladr University Health Board            W11000023    282470

scenario                                                                \
property                                                         BNG_N
region                                             region_code
Aneurin Bevan University Health Board              W11000028    205411
NHS Bath and North East Somerset, Swindon and W... E38000231    154962
Betsi Cadwaladr University Health Board            W11000023    346124

scenario                                                                 \
property                                                           LONG
region                                             region_code
Aneurin Bevan University Health Board              W11000028    -2.9894
NHS Bath and North East Somerset, Swindon and W... E38000231   -2.09676
Betsi Cadwaladr University Health Board            W11000023   -3.75275

scenario                                                                  \
property                                                             LAT
region                                             region_code
Aneurin Bevan University Health Board              W11000028    51.74323
NHS Bath and North East Somerset, Swindon and W... E38000231    51.29374
Betsi Cadwaladr University Health Board            W11000023    52.99951

scenario                                                                                              \
property                                                                                    GlobalID
region                                             region_code
Aneurin Bevan University Health Board              W11000028    b6af30e1-0a47-4411-9621-b2037487094e
NHS Bath and North East Somerset, Swindon and W... E38000231    e0b99a7f-b497-4c8e-8ca9-fe6a8100eb54
Betsi Cadwaladr University Health Board            W11000023    1b0c205c-c731-4c8c-bbf1-f2a32ffead10

scenario                                                                                                           \
property                                                                                                 geometry
region                                             region_code
Aneurin Bevan University Health Board              W11000028    MULTIPOLYGON (((345920.600 181082.100, 345884....
NHS Bath and North East Somerset, Swindon and W... E38000231    POLYGON ((422030.096 199080.267, 420824.313 19...
Betsi Cadwaladr University Health Board            W11000023    MULTIPOLYGON (((270269.001 319142.796, 270191....

scenario                                                                    \
property                                                       region_type
region                                             region_code
Aneurin Bevan University Health Board              W11000028           LHB
NHS Bath and North East Somerset, Swindon and W... E38000231         SICBL
Betsi Cadwaladr University Health Board            W11000023           LHB

scenario                                                                   \
property                                                       short_code
region                                             region_code
Aneurin Bevan University Health Board              W11000028           AB
NHS Bath and North East Somerset, Swindon and W... E38000231           BA
Betsi Cadwaladr University Health Board            W11000023           BC

scenario                                                                 \
property                                                        country
region                                             region_code
Aneurin Bevan University Health Board              W11000028      Wales
NHS Bath and North East Somerset, Swindon and W... E38000231    England
Betsi Cadwaladr University Health Board            W11000023      Wales

scenario                                                                                                           \
property                                                                                                      icb
region                                             region_code
Aneurin Bevan University Health Board              W11000028                                                  NaN
NHS Bath and North East Somerset, Swindon and W... E38000231    NHS Bath and North East Somerset, Swindon and ...
Betsi Cadwaladr University Health Board            W11000023                                                  NaN

scenario                                                                   \
property                                                         icb_code
region                                             region_code
Aneurin Bevan University Health Board              W11000028          NaN
NHS Bath and North East Somerset, Swindon and W... E38000231    E54000040
Betsi Cadwaladr University Health Board            W11000023          NaN

scenario                                                                                             \
property                                                                                       isdn
region                                             region_code
Aneurin Bevan University Health Board              W11000028                                    NaN
NHS Bath and North East Somerset, Swindon and W... E38000231    Gloucester, BSW, BNSSG and Somerset
Betsi Cadwaladr University Health Board            W11000023                                    NaN

scenario                                                                 drip-and-ship  \
property                                                       contains_periphery_lsoa
region                                             region_code
Aneurin Bevan University Health Board              W11000028                         1
NHS Bath and North East Somerset, Swindon and W... E38000231                         1
Betsi Cadwaladr University Health Board            W11000023                         0

scenario                                                                                \
property                                                       contains_periphery_unit
region                                             region_code
Aneurin Bevan University Health Board              W11000028                         0
NHS Bath and North East Somerset, Swindon and W... E38000231                         1
Betsi Cadwaladr University Health Board            W11000023                         0

scenario                                                                    mothership  \
property                                                       contains_periphery_lsoa
region                                             region_code
Aneurin Bevan University Health Board              W11000028                         1
NHS Bath and North East Somerset, Swindon and W... E38000231                         1
Betsi Cadwaladr University Health Board            W11000023                         0

scenario
property                                                       contains_periphery_unit
region                                             region_code
Aneurin Bevan University Health Board              W11000028                         0
NHS Bath and North East Somerset, Swindon and W... E38000231                         0
Betsi Cadwaladr University Health Board            W11000023                         0

In [13]:
gdf_units.head(3)

scenario                                        any             \
property                                stroke_team short_code
postcode
B152TH         Queen Elizabeth Hospital, Birmingham         QE
B714HJ    Sandwell District Hospital, West Bromwich         SW
B95SS                Birmingham Heartlands Hospital         BM

scenario                                                 \
property                          ssnap_name  lsoa_code
postcode
B152TH    Queen Elizabeth Hospital Edgbaston  E01033562
B714HJ            Sandwell District Hospital  E01010104
B95SS         Birmingham Heartlands Hospital  E01009341

scenario                                                                 \
property                                 region region_code region_type
postcode
B152TH    NHS Birmingham and Solihull ICB - 15E   E38000258       SICBL
B714HJ            NHS Black Country ICB - D2P2L   E38000259       SICBL
B95SS     NHS Birmingham and Solihull ICB - 15E   E38000258       SICBL

scenario                                                              \
property  country                                                icb
postcode
B152TH    England  NHS Birmingham and Solihull Integrated Care Board
B714HJ    England            NHS Black Country Integrated Care Board
B95SS     England  NHS Birmingham and Solihull Integrated Care Board

scenario             ... mothership                                  \
property   icb_code  ...    use_msu selected transfer_unit_postcode
postcode             ...
B152TH    E54000055  ...          1        0                nearest
B714HJ    E54000062  ...          0        0                nearest
B95SS     E54000055  ...          0        0                nearest

scenario  drip-and-ship     mothership       any                       \
property periphery_unit periphery_unit     BNG_E     BNG_N   Latitude
postcode
B152TH                0              0  404427.0  283926.0  52.453272
B714HJ                0              0  400919.0  292165.0  52.527357
B95SS                 0              0  411645.0  286935.0  52.480218

scenario
property Longitude                       geometry
postcode
B152TH   -1.936284  POINT (404427.000 283926.000)
B714HJ   -1.987884  POINT (400919.000 292165.000)
B95SS    -1.829966  POINT (411645.000 286935.000)

[3 rows x 28 columns]

In [14]:
gdf_lines_transfer.head(3)

scenario                                              any drip-and-ship  \
property                        transfer_unit_travel_time      selected
postcode transfer_unit_postcode
B152TH   B152TH                                       0.0           0.0
B714HJ   B152TH                                      18.7           0.0
         NaN                                          NaN           NaN

scenario                        mothership       any                       \
property                          selected     BNG_E     BNG_N   Latitude
postcode transfer_unit_postcode
B152TH   B152TH                        0.0  404427.0  283926.0  52.453272
B714HJ   B152TH                        NaN  400919.0  292165.0  52.527357
         NaN                           0.0  400919.0  292165.0  52.527357

scenario                                                                   \
property                        Longitude  BNG_E_mt  BNG_N_mt Latitude_mt
postcode transfer_unit_postcode
B152TH   B152TH                 -1.936284  404427.0  283926.0   52.453272
B714HJ   B152TH                 -1.987884  404427.0  283926.0   52.453272
         NaN                    -1.987884       NaN       NaN         NaN

scenario                                                            \
property                        Longitude_mt           unit_coords
postcode transfer_unit_postcode
B152TH   B152TH                    -1.936284  [404427.0, 283926.0]
B714HJ   B152TH                    -1.936284  [400919.0, 292165.0]
         NaN                             NaN  [400919.0, 292165.0]

scenario                                               \
property                              transfer_coords
postcode transfer_unit_postcode
B152TH   B152TH                  [404427.0, 283926.0]
B714HJ   B152TH                  [404427.0, 283926.0]
         NaN                               [nan, nan]

scenario                                                                       \
property                                                          line_coords
postcode transfer_unit_postcode
B152TH   B152TH                  [[404427.0, 283926.0], [404427.0, 283926.0]]
B714HJ   B152TH                  [[400919.0, 292165.0], [404427.0, 283926.0]]
         NaN                               [[400919.0, 292165.0], [nan, nan]]

scenario
property                                                                  geometry
postcode transfer_unit_postcode
B152TH   B152TH                  LINESTRING (404427.000 283926.000, 404427.000 ...
B714HJ   B152TH                  LINESTRING (400919.000 292165.000, 404427.000 ...
         NaN                           LINESTRING (400919.000 292165.000, nan nan)

In [15]:
gdf_boundaries_lsoa.head(3)

scenario                any                             \
property              BNG_E   BNG_N     LONG       LAT
subtype
lsoa      lsoa_code
Adur 001A E01031349  524915  105607 -0.22737  50.83651
Adur 001B E01031350  524825  106265 -0.22842  50.84244
Adur 001C E01031351  523053  108004   -0.253  50.85845

scenario                                                   \
property                                         GlobalID
subtype
lsoa      lsoa_code
Adur 001A E01031349  ecd2c1ea-25a5-4f52-b374-126691b92f15
Adur 001B E01031350  811f014e-053b-4486-a779-d970f44c9302
Adur 001C E01031351  5b19d5c7-aa66-42fa-9423-6c41a6808b54

scenario                                                                \
property                                                      geometry
subtype
lsoa      lsoa_code
Adur 001A E01031349  POLYGON ((524593.596 105968.135, 525224.777 10...
Adur 001B E01031350  POLYGON ((525001.964 106316.592, 525224.777 10...
Adur 001C E01031351  POLYGON ((524178.373 106053.303, 523763.740 10...

scenario                       diff_drip-and-ship_minus_mothership      \
property            admissions                       utility_shift
subtype                                                       mean std
lsoa      lsoa_code
Adur 001A E01031349   1.333333                                 NaN NaN
Adur 001B E01031350   1.666667                                 NaN NaN
Adur 001C E01031351        2.0                                 NaN NaN

scenario                       ...                 mothership      \
property            mRS shift  ... time_transfer_unit_arrival
subtype                  mean  ...                       mean std
lsoa      lsoa_code            ...
Adur 001A E01031349       NaN  ...                        NaN NaN
Adur 001B E01031350       NaN  ...                        NaN NaN
Adur 001C E01031351       NaN  ...                        NaN NaN

scenario                                                                       \
property            time_puncture     mRS shift     utility_shift     mRS 0-2
subtype                      mean std      mean std          mean std    mean
lsoa      lsoa_code
Adur 001A E01031349           NaN NaN       NaN NaN           NaN NaN     NaN
Adur 001B E01031350           NaN NaN       NaN NaN           NaN NaN     NaN
Adur 001C E01031351           NaN NaN       NaN NaN           NaN NaN     NaN

scenario
property
subtype             std
lsoa      lsoa_code
Adur 001A E01031349 NaN
Adur 001B E01031350 NaN
Adur 001C E01031351 NaN

[3 rows x 61 columns]

In [16]:
gdf_boundaries_catchment.head(3)

     unit                                           geometry drip-and-ship  \
                                                                  selected
0  B152TH  MULTIPOLYGON (((401699.919 267288.105, 401354....           0.0
1  B714HJ  MULTIPOLYGON (((395466.181 272993.528, 395224....           0.0
2  BA13NG  MULTIPOLYGON (((354183.747 145489.704, 353572....           1.0

       mothership
   use   selected use
0  1.0        NaN NaN
1  1.0        NaN NaN
2  1.0        NaN NaN